pipeline {
    agent {
    docker {
        image 'jenkins-docker-agent:latest'
        args '''
          -u root
          -v /var/run/docker.sock:/var/run/docker.sock
          -e HOME=/tmp
        '''
    }
}
    environment {
        AWS_REGION   = 'eu-north-1'
        ECR_REGISTRY = '007079198698.dkr.ecr.eu-north-1.amazonaws.com'
        IMAGE_TAG    = "${BUILD_NUMBER}-${GIT_COMMIT.take(8)}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Agent Tools') {
    steps {
        sh '''
        id
        docker --version
        aws --version
        git --version
        yq --version
        aws sts get-caller-identity
        '''
    }
}

        stage('Login to ECR') {
    steps {
        sh '''
        export HOME=/tmp
        mkdir -p $HOME/.docker

        aws ecr get-login-password --region $AWS_REGION | \
        docker login --username AWS --password-stdin $ECR_REGISTRY
        '''
    }
}

        stage('Build Images') {
    steps {
        sh '''
        docker build \
          -t $ECR_REGISTRY/account-api:$IMAGE_TAG \
          -f src/Services/Account/Account.API/Dockerfile .

        docker build \
          -t $ECR_REGISTRY/ocelot-api-gateway:$IMAGE_TAG \
          -f src/ApiGateways/OcelotApiGateway/Dockerfile .

        docker build \
          -t $ECR_REGISTRY/customer-grpc:$IMAGE_TAG \
          -f src/Services/Customer/Customer.GRPC/Dockerfile .

        docker build \
          -t $ECR_REGISTRY/customer-api:$IMAGE_TAG \
          -f src/Services/Customer/Customer.API/Dockerfile .

        docker build \
          -t $ECR_REGISTRY/transaction-api:$IMAGE_TAG \
          -f src/Services/Transaction/Transaction.API/Dockerfile .

        docker build \
          -t $ECR_REGISTRY/webstatus-ui:$IMAGE_TAG \
          -f src/WebApps/WebStatus/Dockerfile .
        '''
    }
}
        stage('Push Images') {
            steps {
                sh '''
                docker push $ECR_REGISTRY/account-api:$IMAGE_TAG
                docker push $ECR_REGISTRY/ocelot-api-gateway:$IMAGE_TAG
                docker push $ECR_REGISTRY/customer-grpc:$IMAGE_TAG
                docker push $ECR_REGISTRY/customer-api:$IMAGE_TAG
                docker push $ECR_REGISTRY/transaction-api:$IMAGE_TAG
                docker push $ECR_REGISTRY/webstatus-ui:$IMAGE_TAG
                '''
            }
        }

        stage('Debug Workspace') {
    steps {
        sh '''
        pwd
        ls -la
        find . -name ".git" -type d
        '''
    }
}

        stage('Update Helm Values') {
            steps {
                sh '''
                git config user.email "iamwaseemyounas@yahoo.com"
                git config user.name "waseemyounas-bit"

                yq -i '.services.account.image.tag = strenv(IMAGE_TAG)' my-api/values.yaml
                yq -i '.services.api-gateway.image.tag = strenv(IMAGE_TAG)' my-api/values.yaml
                yq -i '.services.customer-grpc.image.tag = strenv(IMAGE_TAG)' my-api/values.yaml
                yq -i '.services.customer-api.image.tag = strenv(IMAGE_TAG)' my-api/values.yaml
                yq -i '.services.transaction.image.tag = strenv(IMAGE_TAG)' my-api/values.yaml
                yq -i '.services.webstatus.image.tag = strenv(IMAGE_TAG)' my-api/values.yaml

                git add my-api/values.yaml
                git commit -m "Update microservice images to $IMAGE_TAG" || echo "No changes to commit"
                git push origin master
                '''
            }
        }
    }

    post {
        success {
            echo "Images pushed and GitOps repo updated with tag: ${IMAGE_TAG}"
        }

        failure {
            echo "Pipeline failed. Check build, ECR login, Docker, or Git push permissions."
        }

        always {
            sh '''
            docker system prune -f || true
            '''
        }
    }
}