replicaCount: 1
imagePullSecrets:
  - name: ecr-regcred

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
volumes: []
volumeMounts: []

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
services:
  account:
    enabled: true
    port: 80
    image:
      repository: 007079198698.dkr.ecr.eu-north-1.amazonaws.com/account-api
      tag: "54-f16d988b"
      pullPolicy: IfNotPresent

  api-gateway:
    enabled: true
    port: 80
    image:
      repository: 007079198698.dkr.ecr.eu-north-1.amazonaws.com/ocelot-api-gateway
      tag: "54-f16d988b"
      pullPolicy: IfNotPresent

  customer-grpc:
    enabled: true
    port: 80
    image:
      repository: 007079198698.dkr.ecr.eu-north-1.amazonaws.com/customer-grpc
      tag: "54-f16d988b"
      pullPolicy: IfNotPresent

  customer-api:
    enabled: true
    port: 80
    image:
      repository: 007079198698.dkr.ecr.eu-north-1.amazonaws.com/customer-api
      tag: "54-f16d988b"
      pullPolicy: IfNotPresent

  transaction:
    enabled: true
    port: 80
    image:
      repository: 007079198698.dkr.ecr.eu-north-1.amazonaws.com/transaction-api
      tag: "54-f16d988b"
      pullPolicy: IfNotPresent

  webstatus:
    enabled: true
    port: 80
    image:
      repository: 007079198698.dkr.ecr.eu-north-1.amazonaws.com/webstatus-ui
      tag: "54-f16d988b"
      pullPolicy: IfNotPresent